# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlineShopGB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnlineShopGB
  pod 'Alamofire', '~> 5.4'
  pod 'SnapKit', '~> 5.0.0'

  target 'OnlineShopGBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnlineShopGBUITests' do
    # Pods for testing
  end

end
